localhost: &localhost
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: localhost

development:
  <<: *localhost
  database: survey_development

test:
  <<: *localhost
  database: survey_test

production:
  <<: *localhost
  database: survey_production